version: "3.9"
services:
    api:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - sqlite_volume:/eindproject/sqlitedb
        environment: 
            PORT: 8000
            FLASK_DEBUG: 1
volumes:
  sqlite_volume: