version: "3.9"
services:
    website:
        labels:
          dev.okteto.com/private: "true"
        build: .
        ports:
            - "8000:8000"
        volumes:
            - sqlite_volume:/eindproject/sqlitedb
        environment: 
            FLASK_DEBUG: 1
volumes:
  sqlite_volume: