version: "3.9"
services:
    api:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - sqlite_volume:/eindproject/sqlitedb
    frontend:
        build: ./frontend
        volumes:
          - './frontend:/app'
          - '/app/node_modules'
        ports:
          - 8080:8080
volumes:
  sqlite_volume:
